public class Test2 {

    public static void show(){
        Integer i=10;
        Long l =45656;
        Decimal d=45.65;
        String s= 'Ganesh';
        Boolean b = False;
        Date dt=date.newInstance(2021,1,15);
       // Id is='4545sa4s5a';
        
       /* System.debug(i);
        System.debug(l);
        System.debug(d);
        System.debug(s);
        System.debug(b);
        System.debug(dt);*/
        
       // System.debug(is);
    }
}